name: Naukri Profile Updater

on:
  # Schedule to run every day at 04:00 UTC (which is 9:30 AM IST)
  schedule:
    - cron: '0 4 * * *'
  
  # Allows you to run this workflow manually from the Actions tab for testing
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the update script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: python main.py
