name: Naukri Profile Updater

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the update script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: python main.py

    # === ADD THIS NEW STEP AT THE END ===
    - name: Upload screenshot artifact on failure
      # This step will only run if the previous step (the script) fails
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: error_screenshot.png
